### PR TITLE
Contribute back several improvements

### PR DESCRIPTION
**Pull request by oehme**
Please excuse the broad scope of this PR, but since you were interested in all the changes I did, I guess there's not much point in splitting it :)

This adds several improvements to the flame graph generation: 

- tlab allocations now measure the tlabSize, the size is converted to kB (fixes https://github.com/chrishantha/jfr-flame-graph/issues/10) 
- blocking is now measured by duration instead of count
- io events are now supported
- the project is now built with Gradle so that there is a 1-step install process (fixes https://github.com/chrishantha/jfr-flame-graph/issues/8) 
- broken stack frames no longer crash the tool (fixes https://github.com/chrishantha/jfr-flame-graph/issues/11) 
- a couple of refactorings to make the code shorter and easier to extend (e.g. adding new event types)

### CODE REVIEW

**Comment by chrishantha** [comment]
Thanks a lot @oehme for the PR. I was bit busy last few days and I couldn't check mails. I will check and merge your changes soon.

**Comment by chrishantha** [comment]
Switching to Gradle is not easy. I miss Maven so much. @oehme I did few changes to master. How do we release in Gradle? I added a gradle plugin, but couldn't check how it works.

**Comment by chrishantha** [comment]
Hi @oehme, I'm sorry, I didn't explain properly. As I mentioned earlier, I'm new to Gradle and I wanna keep using it. In fact, I wanted to try Gradle for a long time and your PR was an opportunity for me to learn it.

I don't publish artifacts, but I use `mvn release:prepare` to tag a version and update to next SNAPSHOT version. How can we do this with Gradle? I assume you have lots of experience with Gradle. :) That's why I wanted to have a conversation with you on this.

Few things I miss in Gradle for now are:

- Use maven release plugin to tag versions
- Use shade plugin to build a fat jar. As an alternative, I use the Gradle distribution directly now and I happy with that approach.

Since Gradle create scripts for both Windows and Linux, I am thinking of moving the flame graph creation logic to Java application.

**Comment by oehme** [comment]
Gradle has the shadow plugin for building fat jars. For tagging and general Git integration I prefer the gradle-git plugin.

**Comment by chrishantha** [comment]
Hi @oehme, I just got to know that you are in the Gradle core team! :) Thanks for the tips.

Could you please give me the links to shadow plugin and gradle-git plugin?

By the way, I meant executing Brendan Gregg's perl script from Java directly when I mentioned about moving FlameGraph creation to the Java. I hope that'll work for you.

**Comment by oehme** [comment]
That still requires Perl on Windows though - I already do that in my project, but Windows doesn't come with Perl by default. Anyway, I may just add some warning instead of moving it to Java completely.

See plugins.gradle.org for plugins.

**Comment by chrishantha** [comment]
Hi @oehme, Thanks for the tip. I updated [README](https://github.com/chrishantha/jfr-flame-graph#how-to-build-and-install) to use `installDist`.

**Pull request merged**
